### ISSUE TITLE
Inconsistencies in rules.md

### ISSUE THREAD

**Issue by Ferdzz** [minecraftforum/documents#14]
Hi, I was reading through https://github.com/minecraftforum/documents/blob/master/rules/rules.md and couldn't help but notice two inconsistencies I didn't want to fix in my PR. In the section [Member / Image postion](https://github.com/minecraftforum/documents/blob/master/rules/rules.md#memberimage-posting), it says "memers". Did you mean "members" or "memes"? Both kind of make sense.

Secondly, in [Wishlists](https://github.com/minecraftforum/documents/blob/master/rules/rules.md#wishlists), it is clearly stated "A wishlist is a thread with a series of unrelated suggestions" however, right after the comma, it says "multiple items per suggestion are permitted as long as they are related". I feel like this is unclear and might be in need of a bit of rephrasing to make sure no one gets confused.

**Comment by shrink** [comment]
Thank you for the feedback! These rules are very much a work in progress, we have a lot of work to do before they're ready for prime time, that includes clarifying quite a few rules and adding some more in too. At present the [Rules](http://www.minecraftforum.net/meta/rules) page on the live website applies. I will update the README to clarify this, as there's no mention of the work in progress status at present.
